### PR TITLE
Casted maxIterations to integer

### PR DESCRIPTION
**Pull request by nicosomb**
Hello, 

I think you should add a cast on `maxIterations` instead of checking if it's an integer in `isRunning()`.

All the other changes come from PHP-CS-Fixer.

We had a problem here https://github.com/wallabag/wallabag/pull/2686

### CODE REVIEW

**Comment by javibravo** [comment]
@nicosomb,

Thanks for contributing. I think could be good idea to do the typecast when assigning the attribute (constructor and setter), in this way the attribute must not be casted every time is used.

Thoughts ?

/cc @yemexx1

**Comment by nicosomb** [comment]
👍 
Will fix that.

**Comment by nicosomb** [comment]
Done.

**Comment by javibravo** [comment]
@nicosomb ,

You missed the setter: https://github.com/nicosomb/simpleue/blob/ca54bc308181e03ff1aff479a900f093292ec522/src/Simpleue/Worker/QueueWorker.php#L45

 Maybe is good idea to use the setter in constructor and assign it only in 1 place.

**Comment by nicosomb** [comment]
> Maybe is good idea to use the setter in constructor

Not sure, but I can do that if you want.

**Comment by javibravo** [comment]
It is fine like this.

Thanks for contributing !!

**Comment by javibravo** [comment]
Released on https://github.com/javibravo/simpleue/releases/tag/1.1.1

**Pull request merged**
